language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-27.0.1
    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    
    # licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
   - ./gradlew build connectedCheck --stacktrace
